### ISSUE TITLE
Разрешите доебаться [Code Review]

### ISSUE THREAD

**Issue by mr-zzq** [ysset/unified_calendar_of_events#1]
Здарова, это не прошеное code review. Все максимально поверхностно, и четко.

Во первых, ваша репа открыта всему миру и при этом отсутствует не то что документация, а даже описание. Я ходил к гадалке Зине, чтобы понять зачем это тут. 
Во вторых, у меня есть несколько назойливых, но очень важных советов:
- **Пишите название репозитория кебаб-кейсом, а не снэйк_кейсом.**
[Это негласное правило](https://stackoverflow.com/questions/11947587/is-there-a-naming-convention-for-git-repositories).
- **Определитесь с код стайлом.**
В коде неоднократно можно заметить присутствие неопределенности с кавычками и точкой с запятой. По [код стайлу google](https://google.github.io/styleguide/jsguide.html) нужно использовать [одинарные ковычки](https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes). И всегда [использовать точку с запятой](https://google.github.io/styleguide/jsguide.html#formatting-semicolons-are-required). И хватить юзать IDE как блокнот. Используйте `Ctrl+Alt+L`(Reformat code).
- **Проверяйте свои комиты.**
В коде есть мусор. https://github.com/ysset/unified_calendar_of_events/blob/f7902f54df7e8ace1a13053c35dfcd6d9817f09e/src/Components/registrationForm/registrationForm.js#L18 Свойство `fontFamily` написана не правильно. Но при этом двумя строками ниже мы видим уже актуальное свойство. 18-я строка просто не нужна.
- **Пишите названия компонентов с большой буквы.**
[На хабре есть старая статья про это(есть еще советы)](https://habr.com/ru/post/347458/)
Я заметил это тут...
https://github.com/ysset/unified_calendar_of_events/blob/f7902f54df7e8ace1a13053c35dfcd6d9817f09e/src/Components/registrationForm/registrationForm.js#L7 И тут... https://github.com/ysset/unified_calendar_of_events/blob/f7902f54df7e8ace1a13053c35dfcd6d9817f09e/src/Components/routes/Routes.js#L6
- **Не используйте анонимные экспорты у компонентов.**
https://github.com/ysset/unified_calendar_of_events/blob/f7902f54df7e8ace1a13053c35dfcd6d9817f09e/src/Components/auhtForm/authForm.js#L7 Вообще в принципе [использование анонимных функций аукается позже](https://stackoverflow.com/a/45667263/12889642).

#### Заключение

Я пытался выделить самое важное. И пропустил орфографию со всякими `auhtForm`, `пороль` и прочее. Надеюсь был полезен. Не забывайте прислушиваться к знающим, и учиться. Нам все таки работать вместе, коллеги.

---

#### Небольшой оффтоп
https://github.com/ysset/unified_calendar_of_events/blob/f7902f54df7e8ace1a13053c35dfcd6d9817f09e/src/Components/auhtForm/authForm.js#L24 Авторизация и аутентификация это два разных термина.
**Аутентификация**|**Авторизация**
:-----:|:-----:
Процедура проверки подлинности субъекта|Процедура присвоения и проверки прав на совершение определенных действий субъектом
Зависит от предоставляемой пользователем информации|Не зависит от действий клиента
Запускается один раз для текущей сессии|Происходит при попытке совершения любых действий пользователем

**Comment by ysset** [comment]
Учтем в виду
